// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.Sokhna.DAL.Data.Contexts;

#nullable disable

namespace Store.Sokhna.DAL.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241225090326_M4")]
    partial class M4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Store.Sokhna.DAL.Models.Equipments", b =>
                {
                    b.Property<int>("Eq_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Eq_ID"));

                    b.Property<string>("DateOfAdding")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("HourCount")
                        .HasColumnType("real");

                    b.Property<float>("HourPrice")
                        .HasColumnType("real");

                    b.Property<string>("Importer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)");

                    b.HasKey("Eq_ID");

                    b.HasIndex("SSN");

                    b.ToTable("Equipmentss");
                });

            modelBuilder.Entity("Store.Sokhna.DAL.Models.Expenses", b =>
                {
                    b.Property<int>("Exp_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Exp_ID"));

                    b.Property<string>("DateOfAdding")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Exp_ID");

                    b.HasIndex("SSN");

                    b.ToTable("Expensess");
                });

            modelBuilder.Entity("Store.Sokhna.DAL.Models.Importers", b =>
                {
                    b.Property<int>("Imp_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Imp_ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Imp_ID");

                    b.ToTable("Importers");
                });

            modelBuilder.Entity("Store.Sokhna.DAL.Models.Pact", b =>
                {
                    b.Property<int>("Pact_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pact_ID"));

                    b.Property<bool>("Confirmed")
                        .HasColumnType("bit");

                    b.Property<string>("DateOfAdding")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfConfirmation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PactAdder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Pact_ID");

                    b.HasIndex("SSN");

                    b.ToTable("Pacts");
                });

            modelBuilder.Entity("Store.Sokhna.DAL.Models.Supplies_Income", b =>
                {
                    b.Property<int>("SI_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SI_ID"));

                    b.Property<string>("DateOfAdding")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Importer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("SupplyAdder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("SI_ID");

                    b.HasIndex("SSN");

                    b.ToTable("Supplies_Incomes");
                });

            modelBuilder.Entity("Store.Sokhna.DAL.Models.Supplies_Outcome", b =>
                {
                    b.Property<int>("SO_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SO_ID"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<float>("CountPrice")
                        .HasColumnType("real");

                    b.Property<string>("DateOfAdding")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Importer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SO_ID");

                    b.HasIndex("SSN");

                    b.ToTable("Supplies_Outcomes");
                });

            modelBuilder.Entity("Store.Sokhna.DAL.Models.Users", b =>
                {
                    b.Property<string>("SSN")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("DateofEmployed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deleted")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("SSN");

                    b.ToTable("Userss");
                });

            modelBuilder.Entity("Store.Sokhna.DAL.Models.Workers", b =>
                {
                    b.Property<int>("W_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("W_ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("W_ID");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("Store.Sokhna.DAL.Models.WorkersSalaries", b =>
                {
                    b.Property<int>("WS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WS_ID"));

                    b.Property<float>("HourCount")
                        .HasColumnType("real");

                    b.Property<float>("HourPrice")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.HasKey("WS_ID");

                    b.ToTable("WorkersSalaries");
                });

            modelBuilder.Entity("Store.Sokhna.DAL.Models.Equipments", b =>
                {
                    b.HasOne("Store.Sokhna.DAL.Models.Users", "Engineer")
                        .WithMany()
                        .HasForeignKey("SSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engineer");
                });

            modelBuilder.Entity("Store.Sokhna.DAL.Models.Expenses", b =>
                {
                    b.HasOne("Store.Sokhna.DAL.Models.Users", "Engineer")
                        .WithMany()
                        .HasForeignKey("SSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engineer");
                });

            modelBuilder.Entity("Store.Sokhna.DAL.Models.Pact", b =>
                {
                    b.HasOne("Store.Sokhna.DAL.Models.Users", "Engineer")
                        .WithMany()
                        .HasForeignKey("SSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engineer");
                });

            modelBuilder.Entity("Store.Sokhna.DAL.Models.Supplies_Income", b =>
                {
                    b.HasOne("Store.Sokhna.DAL.Models.Users", "Engineer")
                        .WithMany()
                        .HasForeignKey("SSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engineer");
                });

            modelBuilder.Entity("Store.Sokhna.DAL.Models.Supplies_Outcome", b =>
                {
                    b.HasOne("Store.Sokhna.DAL.Models.Users", "Engineer")
                        .WithMany()
                        .HasForeignKey("SSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engineer");
                });
#pragma warning restore 612, 618
        }
    }
}
